### ISSUE TITLE
How do you kill polling (on mac?)

### ISSUE THREAD

**Issue by hkirsman** [dcosson/vagrant-unison#10]

**Comment by dcosson** [comment]
Hi, there was a connection bug that was fixed in 1.2.4. Does that release work for you?

If not, can you elaborate on what you mean?

To kill the `unison-sync-polling` command in general, press ctrl+c twice within 2 seconds

**Comment by hkirsman** [comment]
Sometimes it starts to push messages to screen every 1 second and then it's impossible to kill it. Otherwise it seems ctrl + c works.

**Comment by dcosson** [comment]
I've always able to reliably kill by hitting ctrl+c twice in quick succession.

I'm gonna close for now, but if you figure out a fix or idea for a better UI for killing  I'd be happy to review a PR. I do find the feature of hitting ctrl-C once to just terminate the underlying unison process to be useful.
