### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by hkirsman** [dcosson/vagrant-unison#11]
There's something wrong with the unison command. Worked yesterday

**vagrant unison-sync-once**
Unisoning changes from {host}::/Users/hannes/Sites/oc/drupal/current/ --> {guest VM}::/vagrant/drupal/current
Running unison once
    unison /Users/hannes/Sites/oc/drupal/current/ ssh://vagrant@192.168.10.8//vagrant/drupal/current -batch -terse -ignore "Name {.DS_Store,.git,.idea,node_modules}" -perms #Object:0x00000101bfe508 -sshargs "-p 22  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /Users/hannes/Sites/oc/.vagrant/machines/default/vmware_fusion/private_key"
Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]
......
......
unison: option `-perms' needs an argument.

**Comment by hkirsman** [comment]
Ok, so it's a new update #8   and I had to add
config.unison.perms = 0
to my vagrantfile.
Shouldn't it be optional?

**Comment by dcosson** [comment]
Sorry about that! Due to a recent patch, should be fixed in 1.2.4
