### ISSUE TITLE
 Destination updated during synchronization

### ISSUE THREAD

**Issue by hkirsman** [dcosson/vagrant-unison#12]
Synchronization complete at 10:52:30  (1 item transferred, 0 skipped, 0 failed)
changed  ---->            index.php
[BGN] Updating file index.php from /Users/hannes/Sites/site1/drupal/current to //site1.dev//vagrant/drupal/current
Failed: Destination updated during synchronization
The contents of file index.php have been modified

100%  00:00 ETAFailed [index.php]: Destination updated during synchronization
The contents of file index.php have been modified

Synchronization incomplete at 10:52:31  (0 items transferred, 0 skipped, 1 failed)
  failed: index.php

**Comment by dcosson** [comment]
Have you tried `vagrant unison-cleanup` and then running sync again?

Does this happen to you every time you run or was it a one-off thing? Maybe a process within vagrant was actually was modifying the file when you were trying to sync?
