### ISSUE TITLE
The process cannot access the file because it is being used by another process, Unison not running in VM

### ISSUE THREAD

**Issue by stepanzarubin** [dcosson/vagrant-unison#18]
For both:
vagrant unison-sync-once
vagrant unison-sync-polling

Getting:
The process cannot access the file because it is being used by another process.
Unison not running in VM

**Comment by dcosson** [comment]
Is this on windows? Googling it I see this in unrelated circumstances on windows. It sounds like more of a unison or filesystem issue though.

This plugin prints the exact unison command it runs with all the args, so I would try explicitly running that in your VM and seeing what happens/ maybe googing resulting errors or asking about them in a unison forum or something.

Sorry I can't be more helpful :/
