### ISSUE TITLE
Change poll rate

### ISSUE THREAD

**Issue by francislavoie** [dcosson/vagrant-unison#20]
Could we get an option to modify the polling rate? I find every second to be a bit overkill for me and keeping it running all the time is a bit of a CPU hog on Windows (~5-10%). I'd prefer a 5s interval or something like that to relax the CPU usage a bit.

Thanks for this, really did the trick for me! :+1:

**Comment by dcosson** [comment]
This is already configurable. In your Vagrantfile, you can set `config.unison.repeat = 5` to repeat every 5 seconds.

**Comment by francislavoie** [comment]
Oh, cool. Thanks. It's not listed in the README, so I guess that example should be added for the next person to ask :)

**Comment by dcosson** [comment]
Yup, I just added to the README

**Comment by francislavoie** [comment]
Nice.
