### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jujes** [dcosson/vagrant-unison#21]
by default my container create this **user:group** files

```
drwxr-xr-x 2    1000 root    4096 Jun 16 15:11 apps
-rw-r--r-- 1    1000 root    4276 Jun 16 15:06 config.js
drwxr-xr-x 2    1000 root    4096 Jun 16 15:11 data      (database)
drwxr-xr-x 2    1000 root    4096 Jun 16 15:11 images
drwxr-xr-x 4    1000 vagrant 4096 Jun 16 15:11 themes
```

**how I can sync this whitout Permission denied**
Permission denied [rmdir(/....)]

**Comment by dcosson** [comment]
Maybe try `vagrant unison-cleanup` and then sync again? That will try to remove all files in the VM (using sudo) and then re-sync them as the default vagrant user.

I have not tested this on more complicated setups using the non-default vagrant user, I just use a slight variation the vanilla ubuntu vm which basically just has one user, the vagrant user.
